services:
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
